/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as authRouteRouteImport } from './routes/(auth)/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as Errors500RouteImport } from './routes/_errors/500'
import { Route as Errors404RouteImport } from './routes/_errors/404'
import { Route as Errors403RouteImport } from './routes/_errors/403'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as AuthenticatedUnitRouteRouteImport } from './routes/_authenticated/unit/route'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedUnitIndexRouteImport } from './routes/_authenticated/unit/index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedUnitWarningsIndexRouteImport } from './routes/_authenticated/unit/warnings/index'
import { Route as AuthenticatedUnitUsersIndexRouteImport } from './routes/_authenticated/unit/users/index'
import { Route as AuthenticatedUnitSettingsIndexRouteImport } from './routes/_authenticated/unit/settings/index'
import { Route as AuthenticatedUnitRecordsIndexRouteImport } from './routes/_authenticated/unit/records/index'
import { Route as AuthenticatedUnitPanelIndexRouteImport } from './routes/_authenticated/unit/panel/index'
import { Route as AuthenticatedAdminPanelIndexRouteImport } from './routes/_authenticated/admin/panel/index'
import { Route as AuthenticatedUnitUsersStudentsRouteImport } from './routes/_authenticated/unit/users/students'
import { Route as AuthenticatedUnitUsersIdRouteImport } from './routes/_authenticated/unit/users/$id'
import { Route as AuthenticatedAdminPanelIdRouteImport } from './routes/_authenticated/admin/panel/$id'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const authRouteRoute = authRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const Errors500Route = Errors500RouteImport.update({
  id: '/_errors/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const Errors404Route = Errors404RouteImport.update({
  id: '/_errors/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const Errors403Route = Errors403RouteImport.update({
  id: '/_errors/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => authRouteRoute,
} as any)
const AuthenticatedUnitRouteRoute = AuthenticatedUnitRouteRouteImport.update({
  id: '/unit',
  path: '/unit',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUnitIndexRoute = AuthenticatedUnitIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedUnitRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedUnitWarningsIndexRoute =
  AuthenticatedUnitWarningsIndexRouteImport.update({
    id: '/warnings/',
    path: '/warnings/',
    getParentRoute: () => AuthenticatedUnitRouteRoute,
  } as any)
const AuthenticatedUnitUsersIndexRoute =
  AuthenticatedUnitUsersIndexRouteImport.update({
    id: '/users/',
    path: '/users/',
    getParentRoute: () => AuthenticatedUnitRouteRoute,
  } as any)
const AuthenticatedUnitSettingsIndexRoute =
  AuthenticatedUnitSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => AuthenticatedUnitRouteRoute,
  } as any)
const AuthenticatedUnitRecordsIndexRoute =
  AuthenticatedUnitRecordsIndexRouteImport.update({
    id: '/records/',
    path: '/records/',
    getParentRoute: () => AuthenticatedUnitRouteRoute,
  } as any)
const AuthenticatedUnitPanelIndexRoute =
  AuthenticatedUnitPanelIndexRouteImport.update({
    id: '/panel/',
    path: '/panel/',
    getParentRoute: () => AuthenticatedUnitRouteRoute,
  } as any)
const AuthenticatedAdminPanelIndexRoute =
  AuthenticatedAdminPanelIndexRouteImport.update({
    id: '/panel/',
    path: '/panel/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedUnitUsersStudentsRoute =
  AuthenticatedUnitUsersStudentsRouteImport.update({
    id: '/users/students',
    path: '/users/students',
    getParentRoute: () => AuthenticatedUnitRouteRoute,
  } as any)
const AuthenticatedUnitUsersIdRoute =
  AuthenticatedUnitUsersIdRouteImport.update({
    id: '/users/$id',
    path: '/users/$id',
    getParentRoute: () => AuthenticatedUnitRouteRoute,
  } as any)
const AuthenticatedAdminPanelIdRoute =
  AuthenticatedAdminPanelIdRouteImport.update({
    id: '/panel/$id',
    path: '/panel/$id',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/unit': typeof AuthenticatedUnitRouteRouteWithChildren
  '/sign-in': typeof authSignInRoute
  '/403': typeof Errors403Route
  '/404': typeof Errors404Route
  '/500': typeof Errors500Route
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/unit/': typeof AuthenticatedUnitIndexRoute
  '/admin/panel/$id': typeof AuthenticatedAdminPanelIdRoute
  '/unit/users/$id': typeof AuthenticatedUnitUsersIdRoute
  '/unit/users/students': typeof AuthenticatedUnitUsersStudentsRoute
  '/admin/panel/': typeof AuthenticatedAdminPanelIndexRoute
  '/unit/panel/': typeof AuthenticatedUnitPanelIndexRoute
  '/unit/records/': typeof AuthenticatedUnitRecordsIndexRoute
  '/unit/settings/': typeof AuthenticatedUnitSettingsIndexRoute
  '/unit/users/': typeof AuthenticatedUnitUsersIndexRoute
  '/unit/warnings/': typeof AuthenticatedUnitWarningsIndexRoute
}
export interface FileRoutesByTo {
  '/sign-in': typeof authSignInRoute
  '/403': typeof Errors403Route
  '/404': typeof Errors404Route
  '/500': typeof Errors500Route
  '/': typeof AuthenticatedIndexRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/unit': typeof AuthenticatedUnitIndexRoute
  '/admin/panel/$id': typeof AuthenticatedAdminPanelIdRoute
  '/unit/users/$id': typeof AuthenticatedUnitUsersIdRoute
  '/unit/users/students': typeof AuthenticatedUnitUsersStudentsRoute
  '/admin/panel': typeof AuthenticatedAdminPanelIndexRoute
  '/unit/panel': typeof AuthenticatedUnitPanelIndexRoute
  '/unit/records': typeof AuthenticatedUnitRecordsIndexRoute
  '/unit/settings': typeof AuthenticatedUnitSettingsIndexRoute
  '/unit/users': typeof AuthenticatedUnitUsersIndexRoute
  '/unit/warnings': typeof AuthenticatedUnitWarningsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(auth)': typeof authRouteRouteWithChildren
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/unit': typeof AuthenticatedUnitRouteRouteWithChildren
  '/(auth)/sign-in': typeof authSignInRoute
  '/_errors/403': typeof Errors403Route
  '/_errors/404': typeof Errors404Route
  '/_errors/500': typeof Errors500Route
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/unit/': typeof AuthenticatedUnitIndexRoute
  '/_authenticated/admin/panel/$id': typeof AuthenticatedAdminPanelIdRoute
  '/_authenticated/unit/users/$id': typeof AuthenticatedUnitUsersIdRoute
  '/_authenticated/unit/users/students': typeof AuthenticatedUnitUsersStudentsRoute
  '/_authenticated/admin/panel/': typeof AuthenticatedAdminPanelIndexRoute
  '/_authenticated/unit/panel/': typeof AuthenticatedUnitPanelIndexRoute
  '/_authenticated/unit/records/': typeof AuthenticatedUnitRecordsIndexRoute
  '/_authenticated/unit/settings/': typeof AuthenticatedUnitSettingsIndexRoute
  '/_authenticated/unit/users/': typeof AuthenticatedUnitUsersIndexRoute
  '/_authenticated/unit/warnings/': typeof AuthenticatedUnitWarningsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/unit'
    | '/sign-in'
    | '/403'
    | '/404'
    | '/500'
    | '/admin/'
    | '/unit/'
    | '/admin/panel/$id'
    | '/unit/users/$id'
    | '/unit/users/students'
    | '/admin/panel/'
    | '/unit/panel/'
    | '/unit/records/'
    | '/unit/settings/'
    | '/unit/users/'
    | '/unit/warnings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/sign-in'
    | '/403'
    | '/404'
    | '/500'
    | '/'
    | '/admin'
    | '/unit'
    | '/admin/panel/$id'
    | '/unit/users/$id'
    | '/unit/users/students'
    | '/admin/panel'
    | '/unit/panel'
    | '/unit/records'
    | '/unit/settings'
    | '/unit/users'
    | '/unit/warnings'
  id:
    | '__root__'
    | '/(auth)'
    | '/_authenticated'
    | '/_authenticated/admin'
    | '/_authenticated/unit'
    | '/(auth)/sign-in'
    | '/_errors/403'
    | '/_errors/404'
    | '/_errors/500'
    | '/_authenticated/'
    | '/_authenticated/admin/'
    | '/_authenticated/unit/'
    | '/_authenticated/admin/panel/$id'
    | '/_authenticated/unit/users/$id'
    | '/_authenticated/unit/users/students'
    | '/_authenticated/admin/panel/'
    | '/_authenticated/unit/panel/'
    | '/_authenticated/unit/records/'
    | '/_authenticated/unit/settings/'
    | '/_authenticated/unit/users/'
    | '/_authenticated/unit/warnings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  authRouteRoute: typeof authRouteRouteWithChildren
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  Errors403Route: typeof Errors403Route
  Errors404Route: typeof Errors404Route
  Errors500Route: typeof Errors500Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)': {
      id: '/(auth)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_errors/500': {
      id: '/_errors/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof Errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_errors/404': {
      id: '/_errors/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof Errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_errors/403': {
      id: '/_errors/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof Errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/_authenticated/unit': {
      id: '/_authenticated/unit'
      path: '/unit'
      fullPath: '/unit'
      preLoaderRoute: typeof AuthenticatedUnitRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/unit/': {
      id: '/_authenticated/unit/'
      path: '/'
      fullPath: '/unit/'
      preLoaderRoute: typeof AuthenticatedUnitIndexRouteImport
      parentRoute: typeof AuthenticatedUnitRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/unit/warnings/': {
      id: '/_authenticated/unit/warnings/'
      path: '/warnings'
      fullPath: '/unit/warnings/'
      preLoaderRoute: typeof AuthenticatedUnitWarningsIndexRouteImport
      parentRoute: typeof AuthenticatedUnitRouteRoute
    }
    '/_authenticated/unit/users/': {
      id: '/_authenticated/unit/users/'
      path: '/users'
      fullPath: '/unit/users/'
      preLoaderRoute: typeof AuthenticatedUnitUsersIndexRouteImport
      parentRoute: typeof AuthenticatedUnitRouteRoute
    }
    '/_authenticated/unit/settings/': {
      id: '/_authenticated/unit/settings/'
      path: '/settings'
      fullPath: '/unit/settings/'
      preLoaderRoute: typeof AuthenticatedUnitSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedUnitRouteRoute
    }
    '/_authenticated/unit/records/': {
      id: '/_authenticated/unit/records/'
      path: '/records'
      fullPath: '/unit/records/'
      preLoaderRoute: typeof AuthenticatedUnitRecordsIndexRouteImport
      parentRoute: typeof AuthenticatedUnitRouteRoute
    }
    '/_authenticated/unit/panel/': {
      id: '/_authenticated/unit/panel/'
      path: '/panel'
      fullPath: '/unit/panel/'
      preLoaderRoute: typeof AuthenticatedUnitPanelIndexRouteImport
      parentRoute: typeof AuthenticatedUnitRouteRoute
    }
    '/_authenticated/admin/panel/': {
      id: '/_authenticated/admin/panel/'
      path: '/panel'
      fullPath: '/admin/panel/'
      preLoaderRoute: typeof AuthenticatedAdminPanelIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/unit/users/students': {
      id: '/_authenticated/unit/users/students'
      path: '/users/students'
      fullPath: '/unit/users/students'
      preLoaderRoute: typeof AuthenticatedUnitUsersStudentsRouteImport
      parentRoute: typeof AuthenticatedUnitRouteRoute
    }
    '/_authenticated/unit/users/$id': {
      id: '/_authenticated/unit/users/$id'
      path: '/users/$id'
      fullPath: '/unit/users/$id'
      preLoaderRoute: typeof AuthenticatedUnitUsersIdRouteImport
      parentRoute: typeof AuthenticatedUnitRouteRoute
    }
    '/_authenticated/admin/panel/$id': {
      id: '/_authenticated/admin/panel/$id'
      path: '/panel/$id'
      fullPath: '/admin/panel/$id'
      preLoaderRoute: typeof AuthenticatedAdminPanelIdRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
  }
}

interface authRouteRouteChildren {
  authSignInRoute: typeof authSignInRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authSignInRoute: authSignInRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminPanelIdRoute: typeof AuthenticatedAdminPanelIdRoute
  AuthenticatedAdminPanelIndexRoute: typeof AuthenticatedAdminPanelIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
    AuthenticatedAdminPanelIdRoute: AuthenticatedAdminPanelIdRoute,
    AuthenticatedAdminPanelIndexRoute: AuthenticatedAdminPanelIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedUnitRouteRouteChildren {
  AuthenticatedUnitIndexRoute: typeof AuthenticatedUnitIndexRoute
  AuthenticatedUnitUsersIdRoute: typeof AuthenticatedUnitUsersIdRoute
  AuthenticatedUnitUsersStudentsRoute: typeof AuthenticatedUnitUsersStudentsRoute
  AuthenticatedUnitPanelIndexRoute: typeof AuthenticatedUnitPanelIndexRoute
  AuthenticatedUnitRecordsIndexRoute: typeof AuthenticatedUnitRecordsIndexRoute
  AuthenticatedUnitSettingsIndexRoute: typeof AuthenticatedUnitSettingsIndexRoute
  AuthenticatedUnitUsersIndexRoute: typeof AuthenticatedUnitUsersIndexRoute
  AuthenticatedUnitWarningsIndexRoute: typeof AuthenticatedUnitWarningsIndexRoute
}

const AuthenticatedUnitRouteRouteChildren: AuthenticatedUnitRouteRouteChildren =
  {
    AuthenticatedUnitIndexRoute: AuthenticatedUnitIndexRoute,
    AuthenticatedUnitUsersIdRoute: AuthenticatedUnitUsersIdRoute,
    AuthenticatedUnitUsersStudentsRoute: AuthenticatedUnitUsersStudentsRoute,
    AuthenticatedUnitPanelIndexRoute: AuthenticatedUnitPanelIndexRoute,
    AuthenticatedUnitRecordsIndexRoute: AuthenticatedUnitRecordsIndexRoute,
    AuthenticatedUnitSettingsIndexRoute: AuthenticatedUnitSettingsIndexRoute,
    AuthenticatedUnitUsersIndexRoute: AuthenticatedUnitUsersIndexRoute,
    AuthenticatedUnitWarningsIndexRoute: AuthenticatedUnitWarningsIndexRoute,
  }

const AuthenticatedUnitRouteRouteWithChildren =
  AuthenticatedUnitRouteRoute._addFileChildren(
    AuthenticatedUnitRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedUnitRouteRoute: typeof AuthenticatedUnitRouteRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedUnitRouteRoute: AuthenticatedUnitRouteRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  authRouteRoute: authRouteRouteWithChildren,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  Errors403Route: Errors403Route,
  Errors404Route: Errors404Route,
  Errors500Route: Errors500Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
